apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name.nameservice }}
  labels:
    app: {{ .Values.service.name.nameservice }}-{{ .Release.Namespace }}
    app.kubernetes.io/name: {{ .Values.service.name.nameservice }}
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.service.name.nameservice }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
        {{- range $key, $val := .Values.annotations }}
        {{ $key }}: {{ $val }}
        {{- end }}
      labels:
        app: {{ .Values.service.name.nameservice }}-{{ .Release.Namespace }}
        app.kubernetes.io/name: {{ .Values.service.name.nameservice }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag.nameservice }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- range $arg := .Values.args }}
            - {{ $arg }}
            {{- end }}
          env:
            - name: SERVICE_NAME
              value: "{{ .Values.service.name.nameservice }}"
            - name: CLUSTER_IDENTIFIER
              value: "{{ .Values.service.identifier }}"
            - name: server.port
              value: "{{ .Values.service.port.nameservice }}"
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
          ports:
            {{- range $key, $val := .Values.additionalPorts }}
            - name: {{ $key }}
              containerPort: {{ $val }}
              protocol: TCP
            {{- end }}
{{ if .Values.service.enabled }}
            - name: http
              containerPort: {{ .Values.service.port.nameservice }}
              protocol: TCP
{{ if eq .Values.probe.type "tcp" }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port.nameservice }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port.nameservice }}
            initialDelaySeconds: 15
            periodSeconds: 30
{{ else }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.path }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.path }}
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
{{ end }}
{{ end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
    name: {{ .Values.service.name.nameservice }}
    namespace: {{ .Release.Namespace }}
spec:
    maxReplicas: 100
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1beta1
      kind: Deployment
      name: {{ .Values.service.name.nameservice }}
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 65
